osx_image: xcode9.3
language: objective-c
xcode_workspace: Example/CUU.xcworkspace
xcode_scheme:
    - CUU-Example
xcode_sdk:
    - iphonesimulator11.3
podfile: Example/Podfile

before_install:
    - gem install cocoapods
    - pod install --project-directory=Example